Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/06/2024
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

Escreval("Nome: Gustavo")
Escreval("Idade: ", 29)
Escreval("Altura: ", 1.89)
Escreval("Adulto: ", verdadeiro)

Fimalgoritmo