Algoritmo "1-)PARA-Aninhados"

Var
//EU POSSO TER UM PARA DENTRO DE OUTRO PARA
i,j: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para i de 1 ate 10 faca //PARA CADA 1 EXECUÇÃO DO (i), TEMOS 3 EXECUÇÕES DO (j)
     escreval("valor de i: ", i)//PARA CADA 1 EXECUÇÃO DO (i), TEMOS 3 EXECUÇÕES DO (j)
   para j de 1 ate 3 faca
     escreval("J: ", j)
   fimpara
   fimpara

Fimalgoritmo