Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/05/2024
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Olá Mundo") //para testar digite a linha ao lado
//OBSERVAÇÃO: AS PALAVRAS EM AZUIS SÃO RESERVADAS
Fimalgoritmo